# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d802198d603712a457c41b699a38656d003ba7b09faa6452a4285e022e724805224c1a22bc2d9690f72eac964defcc9ea9c7e307b04b27014c281e753ded429e

test:
  secret_key_base: 1efaa9d9482bd449c2587aa5e33b89d0800fba1fdc67bc168c5e80b9b7571ffb287e130691c12e2599538c3ba56f0e869fc178b9ebf48789d8b94d4c1565fea3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
